"""bootstrap database

Revision ID: 552ecb5afcf6
Revises: 8f2a5ff81478
Create Date: 2020-09-05 11:06:43.207212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552ecb5afcf6'
down_revision = '8f2a5ff81478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
