"""bootstrap database

Revision ID: ad6e81f4eb33
Revises: 552ecb5afcf6
Create Date: 2020-09-05 11:10:01.309001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6e81f4eb33'
down_revision = '552ecb5afcf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
