"""refactor user

Revision ID: afa15995d8ad
Revises: ad6e81f4eb33
Create Date: 2020-09-05 11:29:51.883068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa15995d8ad'
down_revision = 'ad6e81f4eb33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.String(length=3000), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('old_id', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('status', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'status')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'old_id')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'email')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
